# Generated by Django 3.0.5 on 2020-04-18 01:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=255)),
                ('confirmados', models.IntegerField(default=0)),
                ('obitos', models.IntegerField(default=0)),
                ('descartados', models.IntegerField(default=0)),
                ('investigacao', models.IntegerField(default=0)),
                ('data_boletim', models.DateField()),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
