# Generated by Django 3.0.5 on 2020-04-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletim',
            name='estado',
            field=models.CharField(default='PR', max_length=2),
        ),
    ]
